### ISSUE TITLE
Pyserial Read Delays

### ISSUE THREAD

**Issue by ajowsey** [mraardvark/pyupdi#13]
In your send command for Physical.py, your pyserial read appears to add an additional 1 second delay between sent bytes. Not sure if its needed.  I was able to reproduce it on multiple devices

Line 83
# Echo
self.ser.read()

**Comment by mraardvark** [comment]
With TX and RX tied together, each byte sent will also be received - this is why read() is called.  
There are probably other ways to do this - perhaps a flush?
