### ISSUE TITLE
Support for megaAVR 0-series

### ISSUE THREAD

**Issue by fschneidereit** [mraardvark/pyupdi#21]
Support for the ATmega3208/3209/4808/4809 would be great.

**Comment by mraardvark** [comment]
Technically UPDI is the same on the megas, but the flash starts at 0x4000.

**Comment by fschneidereit** [comment]
I don't work with these devices at the moment, but would contribute the necessary code if flash address is the only difference. What about the ATtiny3216/3217? Telling from the data sheet, its the same as all the other tinyAVR 1-series devices, except for flash size.

**Comment by mraardvark** [comment]
I have a mega4809 here, but need to do a spot of soldering to use pyupdi...  will note-to-self to try to get it done...

**Comment by fschneidereit** [comment]
OK. The page size is also different on the megas (128). I pushed a version with megaAVR support to my fork of pyupdi, you can use it for experimenting if you like.

**Comment by mraardvark** [comment]
Thanks.  I did a cut-and-paste over and pushed.  Tested with led blinker on m4809.

**Comment by fschneidereit** [comment]
:+1:
