### ISSUE TITLE
Option for sending CHIPERASE and NVMPROG keys at the same time

### ISSUE THREAD

**Issue by leonerd** [mraardvark/pyupdi#26]
Hi there,

First off - thanks for writing and publishing this. It has been a great help to me in writing my own UPDI-talking code.

I would like to draw your attention to a curious quirk of the way the chips work, that can sometimes be hard to get out of. I discussed it on

  https://www.avrfreaks.net/forum/attiny814-not-accepting-nvmprog-key#comment-2706166

but in summary: if you write a bad fuse value to SYSCFG0 it requires you to load both CHIPERASE and NVMPROG keys at the same time before you issue the system reset request, in order to get out of it.

I have a added an option to do that to my own code, you may wish to add similar to yours.

**Comment by mraardvark** [comment]
thanks for the reminder :)
PR in the making...
