### ISSUE TITLE
Read out fuses

### ISSUE THREAD

**Issue by danupp** [mraardvark/pyupdi#34]
Cheers and thanks for a very useful tool!
Any thoughts about adding an option to read out the fuse bits? I notice that the underlying code is already there and what's missing is more or less just an argument to the parser.

**Comment by mraardvark** [comment]
@danupp I don't really have intention to add features myself; except for device support, for example the DA parts "coming soon" (https://www.microchip.com/wwwproducts/en/AVR128DA28) which will need some mods for 128k support.
But please feel free to make a feature addition and put in a pull request - I will try to test it at least...
