### ISSUE TITLE
EEPROM Programming

### ISSUE THREAD

**Issue by ccvelandres** [mraardvark/pyupdi#71]
Is it possible to add eeprom read/write to pyupdi? By my understanding, the NVM Controller also allows read/writing to the EEPROM. So it should be just the same approach as flash programming with just different address right?

**Comment by mraardvark** [comment]
I recommend you look at pymcuprog - using the "-t uart" tool, you can access pyupdi.
EEPROM is of course supported.
Latest on pypi test server: pip install -i https://test.pypi.org/simple/ pymcuprog

**Comment by ccvelandres** [comment]
Got it to work. Thanks!

**Comment by mraardvark** [comment]
Good to hear it 👍 
(The version from test.pypi will be promoted to pypi production server in the coming weeks.)
