### ISSUE TITLE
Need support for ATtiny1624

### ISSUE THREAD

**Issue by mechatroniks-git** [mraardvark/pyupdi#82]
`pyupdi -d tiny1624 -c COM8 -b 38400 -fs 10:0x00`

This works with tiny1614, but not tiny1624, as the device is not recognized.

PYMUCPROG doesn't support burning the lock fuse, or I haven't found a way to do it, so I've been using pyupdi for all my lockbit needs.

**Comment by xedbg** [comment]
pymcuprog write -m lockbits -l value-to-write
